config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
   root to: 'foodstalls#index'
   get 'foodstalls/search'
   resources :users, only: [:show]
  resources :foodstalls do
    resources :store_reservations, only: [:new, :confirmation, :create] do
      collection do
        post :confirmation
      end
    end
    resources :comments, only: [:new, :create]
     member do
       get 'search'
     end
  end
end

app/models/foodstall.rb
class Foodstall < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
   belongs_to :owner
   belongs_to_active_hash :category
   belongs_to_active_hash :prefecture
   has_many_attached :images
   has_many :store_reservations
   has_many :comments
  
   
  with_options presence: true do
    validates :title
    validates :images
    validates :shop_name
    validates :text
    validates :city_name
    validates :address
    validates :building_name
    with_options format: { with: /\A\d{3}[-]\d{4}\z/} do
    validates :post_code
    end
    with_options format: { with: /\A\d{10,11}\z/} do
    validates :phone_number
    end
    validates :category_id
    validates :prefecture_id
   end
   def avg_raty
    unless self.comments.empty?
      comments.average(:raty).round(1).to_f
    else
      0.0
    end
  end
  def avg_raty_percentage
    unless self.comments.empty?
      comments.average(:raty).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/controllers/foodstalls_controller.rb
class FoodstallsController < ApplicationController
  before_action :authenticate_owner!, only: [:new]
  before_action :search_foodstall, only: [:index, :search]
  def index
    @foodstalls = Foodstall.all
     set_foodstall_column
    @results = @p.result
    @prefecture = Prefecture.where(params[:id])
    @category = Category.where(params[:id])
    @comment = Comment.all
    @all_ranks = Comment.where(foodstall_id: @foodstalls.ids, raty: @comment.ids).order('raty desc').limit(3)
  end

  def new
    @foodstall = Foodstall.new
  end

  def create
      @foodstall = Foodstall.new(foodstall_params)
      @comment = Comment.new
  if @foodstall.save
    redirect_to foodstalls_path(:foodstall_id)
else
  render :new
  end
 end

 def search
  @foodstalls = Foodstall.all
  @results = @p.result
  @category = Category.where(params[:id])
  @prefecture = Prefecture.where(params[:id])
  @comments = Comment.where(foodstall_id: @foodstalls.ids)
 end

 def show
  @foodstall = Foodstall.find(params[:id])
  @date = Date.today
  @wdays = ['月','火','水','木','金','土','日']
  #@comments = @foodstall.comments
  @comments = Comment.where(foodstall_id: @foodstall.id)
 end

  private
  def foodstall_params
    params.require(:foodstall).permit(:category_id, :shop_name, :post_code, :city_name, :address, :phone_number, :building_name, :prefecture_id, :title, :text, images: []).merge(owner_id: current_owner.id)
  end
  def set_q
    @p = Foodstall.ransack(params[:q])
  end

  def search_foodstall
    @p = Foodstall.ransack(params[:q])  
  end
  def set_foodstall_column
    @foodstall_category_name = Foodstall.select("category").distinct
    @foodstall_prefecture_name = Foodstall.select("prefecture").distinct
  end
  
end

app/helpers/foodstalls_helper.rb
module FoodstallsHelper
  
end

app/views/foodstalls/index.html.erb
<header class="header-index">
<img src="/assets/main10.jpg">
<div class="main">
  <% if owner_signed_in?%>
  <%= render "owners/shared/header" %>
  <%else%>
  <%= render "users/shared/header" %>
  <%end%>
  </header>
</div>
 <div class="home-title">
   <h2>週末はみんなでchill しよう</h2>
</div> 
<dl class="keyword">
  <dt>
   <%= search_form_for @p, url: foodstalls_search_path do |f| %>
     <%= f.label :category_eq, 'カテゴリー' %> 
        <%= f.collection_select(:category_id_eq, @category, :id, :name, include_blank: '指定なし' )%>
        <%= f.label :prefecture_id_eq, '都道府県' %>
      <%= f.collection_select(:prefecture_id_eq, @prefecture, :id, :name, include_blank: '指定なし'  )%>
   <%=f.text_field :title_or_shop_name_or_city_name_cont, placeholder: "キーワード"%>
  </dt>
  <dd>
   <%= f.submit "検索", class: 'keyword-btn'%>
  </dd>
  <% end %>

</dl>

  
</div>
  <div class="home-text">
    <h1 class="home-text-header">リラックスするお店を探す時はchillアプリ</h1>
    <p class="home-text-a">このアプリは、個室や眺めのいい景色が見えるお店、今流行りのシーシャ屋を探したり予約をすることもできます</p>
    <p class="home-text-b">お店を経営している人は、このアプリに掲載させることができる機能があります</p>
  </div>
  <h1 class="home-description-title">機能説明</h1>
   <div class="home-description">
      <div class="home-description-left">
         <h2>キーワード検索機能</h2>
         <%= image_tag 'main5.png', class: 'image-left'%>
      </div>
      <div class="home-description-center">
        <h2>オーナー出店機能</h2>
        <%=  image_tag 'new-owner.jpg', class: 'image-center'%>
      </div>
      <div class="home-description-right">
        <h2>予約機能</h2>
        <%= image_tag 'main4.png', class: 'image-right'%>
      </div>
   </div>
   
 
   <div class= "index-footer">
   <% if owner_signed_in?%>
  <%= render "owners/shared/footer" %>
  <%else%>
  <%= render "users/shared/footer" %>
  <%end%>
  </div>

app/views/foodstalls/new.html.erb
<div class="new-group">
  <h3 class="container">
    新規出店
  </h3>
    <%= form_with(model: @foodstall, local: true) do |f| %>
    <div class="img-upload">
      <div class="weight-bold-text">
        店内画像
        <span class="indispensable">必須</span>
      </div>
     <div class="click-upload">
      <p>
       店内写真
      </p>
            <%= f.label :images, "画像アップロード", class: "image_input_btn"  %>
            <div id="foodstall-image"><%= f.file_field :images, name: 'foodstall[images][]', style: 'display:none'  %></div>
            <div id="image-list"></div>
          
     </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ジャンル</label>
          <span class="indispensable">必須</span>
      </div>
       <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>  
      
      <div class='form-text-wrap'>
        <label class="form-text">店舗紹介タイトル</label>
          <span class="indispensable">必須</span>
      </div>
         <%= f.text_field :title, {class: 'form-title'} %>

        <div class='form-text-wrap'>
            <label class="form-text">店舗紹介</label>
              <span class="indispensable">必須</span>
        </div>
              <%= f.text_area :text, {class: 'form-text'}%>
         
      
        <div class='form-text-wrap'>
          <label class="form-text">店舗名</label>
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_field :shop_name, class:"form-shop_name", id:"shop-name", placeholder:"例）セブンイレブン" %> 
      
     
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_field :post_code, class:"form-post_code", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %> 
      
      
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
          <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"form-prefecture", id:"prefecture"}) %>  
      
     

        <div class='form-text-wrap'>
          <label class="form-text">住所</label>
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_field :city_name, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%> 
      
      
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_field :address, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%> 
      
      
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">必須</span>
        </div>
         <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%> 
      
     
        <div class='form-text-wrap'>
          <label class="form-text">店舗の電話番号</label>
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_field :phone_number, class:"form-phone-number", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%> 
      
    </div>
    <div class="foodstall-bottom">
      <%= f.submit "出店する", class: "foodstall-bottan"  %>
      <%=link_to 'もどる', root_path, {class: "nav-link"}%>
    </div>
    <div id="image-list"></div>
    <% end %>
</div>
    <% @foodstall.images.each do |foodstall| %>
  <%= image_tag image, class: 'images' %>
<% end %>

app/views/foodstalls/search.html.erb
<% if owner_signed_in?%>
  <%= render "owners/shared/header" %>
  <%else%>
  <%= render "users/shared/header" %>
  <%end%>

<h1 class= "list-search">
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>
 <% @results.each do |result| %>
  <br>
   <li class="list">
    <div class="list-top">
      <h2 class="list-title">
        <%= link_to foodstall_path(result.id), class:'list-title-name' do %>
        <%= result.shop_name%>
      </h2>
      <p class="list-category"><%= result.category.name %></p>
       <% end %>
    </div>
      <h4 class= "list-perfecture" >
         <%= result.prefecture.name %>
      </h4>
      <div class="list-text">
        <p><nobr><%= result.city_name %><%= result.address%><%= result.building_name%></nobr></p>
          <div class="average-search">
            <% @ar = Comment.where(foodstall_id: result.id).select(:raty) %>
            <% if @ar == [] %>
            <% @avg = 0 %>
            <%else%>
            <% @avg = @ar.average(:raty).round(1) %>
            <%end%>
            <nobr><%= @avg %>点</nobr>
            <span id="star-rate-<%= result.id %>"></span>
          </div>
      </div>
      <%= link_to foodstall_path(result.id) do %>
           <%= image_tag result.images[0], class:'images' %>
        <% end %>
   </li>
  <script>
    $('#star-rate-<%= result.id %>').raty({
      size: 36,
      starOff: "<%= asset_path('star-off.png') %>",
      starOn: "<%= asset_path('star-on.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      half: true,   
      readOnly: true,  
      score: <%= @avg %>,  
    });
  </script>
 <% end %>
<% else %>
  該当する商品はありません
<% end %>


<h3 class= "search-back">
 <%= link_to 'トップページへ戻る', root_path, class: 'search-back-name' %>
 </h3>
 

app/views/foodstalls/show.html.erb
<div class="foodstall-show">
<% if owner_signed_in?%>
  <%= render "owners/shared/header" %>
<%else%>
  <%= render "users/shared/header" %>
<%end%>
  <div class="foodstall-show-image">
    <% @foodstall.images.each do |image|%>
     <%= image_tag  image %>
    <% end %>
  </div>

  <div class="foodstall-show-title">
   <h1>
     <%= @foodstall.shop_name %>
   </h1>
  </div>
<%# 星型のレビュー平均値 %>
  <div class= average-raty>
    <%= @foodstall.avg_raty %>点(<%= @foodstall.comments.count %>件のレビュー)
  </div>

  <div class="footstall-category">
   <h5>
    <%= @foodstall.category.name%>
   </h5>
  </div>

  <div class="foodstall-title">
   <h2><%=@foodstall.title%></h2>
  </div>

  <div class="foodstall-text">
    <p><%=@foodstall.text%></p>
  </div>

<div class="addresses">
  <div class="foodstall-post">
    <%= @foodstall.post_code %>
  </div>
   <div class="foodstall-prefecture">
     <%= @foodstall.prefecture.name%>
   </div>
   <div class="foodstall-adress">
     <%= @foodstall.address %>
   </div>
  <div class="foodstall-building">
   <%= @foodstall.building_name %>
  </div>
</div>
<div class="calendar">
<p>
  <%= @today&.strftime("< %m / %Y >") %>
</p>
<table border="1">
    <tr>
    <th>時間</th>
    <% 10.times do |n| %>
    <th> 
      <% @th_date =  Date.today + n %>
      <% @th_header = @th_date.strftime("%m/%d %a") %>
      <%= @th_header %>
    </th>
  <%end%>
    </tr>
    <% 9.times do |i|%>
    <tr>
      <th>
        <% @th_time = Time.new(2021,7,22,i+10,00,00) %>
        <%= @th_time.strftime("%H:%M") %>
      </th>
      <% 10.times do |d| %>
      <td>
        <% @th_date =  Date.today + d %>
        <% if @td_number = StoreReservation.where(foodstall_id: @foodstall.id,visit_date_time: DateTime.new(@th_date.year, @th_date.month, @th_date.day, @th_time.hour, @th_time.min, @th_time.sec)).blank?%>
        <%= link_to "○", new_foodstall_store_reservation_path(foodstall_id: @foodstall.id, re_date: @th_date, re_time: @th_time.hour) %>
        <% else %>
        <span>×<span>
        <%end%>
      </td>
      <% end %>
    </tr>
    <% end %>
</table>
</div>

<div class="foodstall-show-phone_number">
   <%= @foodstall.phone_number%>
 </div>

<div class="show-comment">
<h1>口コミ一覧</h1>
<% if user_signed_in? %>
<%= link_to '口コミを投稿する', new_foodstall_comment_path(foodstall_id: @foodstall.id) %>
<%else%>
<%end%>
<% @comments.each do |comment|%>
<p><strong><%= comment.user.name %></strong>
 <p><%= comment.text %></p>
 <p>投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %></p>
 <div class="relative-post-evaluation">
  <span>評価：</span>
  <span id="star-rate-<%= comment.id %>"></span>
  <script>
    $('#star-rate-<%= comment.id %>').raty({
      size: 36,
      starOff: "<%= asset_path('star-off.png') %>",
      starOn: "<%= asset_path('star-on.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      half: true,   
      readOnly: true,  
      score: <%= comment.raty %>,  
    });
  </script>
  <%= comment.raty %>
 </div>
<% end %>
</div>
<div class="show-root_back">
<%= link_to foodstalls_search_path do %>
  <p class= "show-back">戻る</p>
<% end %>
</div>
</div>