config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
   root to: 'foodstalls#index'
   get 'foodstalls/search'
   resources :users, only: [:show]
  resources :foodstalls do
    resources :store_reservations, only: [:new, :confirmation, :create] do
      collection do
        post :confirmation
      end
    end
    resources :comments, only: [:new, :create]
     member do
       get 'search'
     end
  end
end

app/models/store_reservation.rb
class StoreReservation < ApplicationRecord
  belongs_to :user
  belongs_to :foodstall


  validates :visit_date_time, presence: true 
  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/controllers/store_reservations_controller.rb
class StoreReservationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :confirmation, :create]
  def new
    @store_reservation = StoreReservation.new
  end
  def confirmation
    @prev_store_reservation = StoreReservation.new(store_reservations_params)
    @new_store_reservation = StoreReservation.new
  end

  def create
    @store_reservation = StoreReservation.new(store_reservations_params)

    @store_reservation.user_id = current_user.id
    @store_reservation.foodstall_id = params[:foodstall_id]
    if @store_reservation.save
      redirect_to foodstall_path(params[:foodstall_id])
    else
      render 'new'
    end
  end

  private
  def store_reservations_params
    params.require(:store_reservation).permit(:visit_date_time, :phone_number, :email, :name).merge(user_id: current_user.id, foodstall_id: params[:foodstall_id])
  end
end

app/helpers/store_reservation_helper.rb
module StoreReservationHelper
end

app/views/store_reservations/confirmation.html.erb
<div class="prev">
      <h1>確認画面</h1>
        <div class="prev-name">
            <h3>名前</h3>
              <%= @prev_store_reservation.name %>
        </div>
        <div class="prev-email">
             <h3>メールアドレス</h3>
              <%= @prev_store_reservation.email %>
         </div>
         <div class="prev-phone_number">
           <h3>携帯電話</h3>
           <%= @prev_store_reservation.phone_number %>
         </div>
         <div class="prev-visit_date_time">
           <h3>予約時間</h3>
           <%= @prev_store_reservation.visit_date_time.strftime("%Y年%-m月%-d日 %H:%M") %>
         </div>
                  <%= form_with model: @new_store_reservation, url: foodstall_store_reservations_path(foodstall_id: params[:foodstall_id]), method: :post, local: true do |f| %>
                    <%= f.hidden_field :name, value: @prev_store_reservation.name %>
                    <%= f.hidden_field :email, value: @prev_store_reservation.email %>
                    <%= f.hidden_field :phone_number, value: @prev_store_reservation.phone_number %>
                    <%= f.hidden_field :visit_date_time, value: @prev_store_reservation.visit_date_time %>
         <div class="actions">
                <%= f.submit '予約する', class: "actions-btn" %>
                <%= link_to '戻る', foodstall_path(params[:foodstall_id]), {class: "prev-nav-link"} %>
          </div>
    <% end %>
</div>

app/views/store_reservations/confirmationhtml.erb
<%= form_for @store_reservation do |f| %>
  <%= @store_reservation.name %>
  <%= @store_reservation.emai %>
  <%= @store_reservation.phone_number%>
  <div class="actions">
    <%= f.submit '投稿画面に戻る', name: 'back' %>
  </div>
  <div class="actions">
    <%= f.submit '投稿する' %>
  </div>
<% end %>

app/views/store_reservations/new.html.erb
<div class="new-store_reservation">

  <h1>予約フォーム</h1>
    <%= form_with model: @store_reservation, url: confirmation_foodstall_store_reservations_path(params[:foodstall_id]), local: true do |f| %>
    <div class="new-form-group">
      <div class='new-form-text-wrap'>
         <h3><label class="form-text">名前</label>
           <span class="indispensable">必須</span></h3>
      </div>
           <%= f.text_field :name%>
    </div>

        <div class="new-form-group">
          <div class='form-text-wrap'>
            <h3><label class="form-text">メールアドレス</label>
            <span class="indispensable">必須</span></h3>
          </div>
          <%= f.text_field :email, class:"input-default", id:"email", placeholder:"例）aaaa@gmail.com" %> 
        </div>

      <div class="new-form-group">
          <div class='form-text-wrap'>
            <h3><label class="form-text">電話番号</label>
            <span class="indispensable">必須</span></h3>
          </div> 
          <%= f.text_field :phone_number, class:"new-input-default", id:"phone-number", placeholder:"例）08011112222", maxlength:"11" %> 
          </div>

          <div class="new-form-group">
            <div class='form-text-wrap'>
              <h3><label class="form-text">予約</label>
              <span class="indispensable">日程</span></h3>
            </div>
            <% re_date = params[:re_date].to_date %>
            <%= re_date.strftime("%Y年%-m月%-d日") %> <%= params[:re_time] + "時より" %>
            <%= f.hidden_field :visit_date_time, value: DateTime.new(re_date.year,re_date.month,re_date.day,params[:re_time].to_i,00,00) %> 
            </div>


          <div class="store_reservation-bottan">
        <%= f.submit "予約確認画面"  %>
        <%=link_to 'もどる', foodstall_path(params[:foodstall_id]), {class: "new-nav-link"} %>
      </div>
      <%end%>
</div>
    